export const GamePhaseEnum = {
  SETUP: 'SETUP',
  START: 'START',
  ROLLING: 'ROLLING',
  SCENARIO_PENDING: 'SCENARIO_PENDING',
  SCENARIO_CHOICE: 'SCENARIO_CHOICE',
  SCENARIO_OUTCOME: 'SCENARIO_OUTCOME',
  CHANCE: 'CHANCE',
  ERROR: 'ERROR',
  GAME_OVER: 'GAME_OVER',
} as const;
