name: Deploy to GitHub Pages and Branch Previews

on:
  push:
    branches:
      - '**'
  delete:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      sanitized_branch_name: ${{ steps.sanitize.outputs.sanitized_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Sanitize branch name
        id: sanitize
        run: |
          sanitized_name=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9]/-/g')
          echo "sanitized_name=${sanitized_name}" >> $GITHUB_OUTPUT

      - name: Set Base URL
        run: |
          sanitized_name=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9]/-/g')
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "VITE_BASE_PATH=/${{ github.event.repository.name }}/" >> $GITHUB_ENV
          else
            echo "VITE_BASE_PATH=/${{ github.event.repository.name }}/branches/${sanitized_name}/" >> $GITHUB_ENV
          fi

      - name: Build
        run: npm run build
        env:
          VITE_BASE_PATH: ${{ env.VITE_BASE_PATH }}
          GITHUB_PAGES: true

      - name: Copy locales to dist
        run: cp -r locales dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ github.ref_name == 'main' && '.' || format('branches/{0}', needs.build.outputs.sanitized_branch_name) }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploying branch ${{ github.ref_name }} to GitHub Pages"

  cleanup:
    runs-on: ubuntu-latest
    if: github.event_name == 'delete'
    steps:
      - name: Sanitize branch name
        id: sanitize
        run: |
          sanitized_name=$(echo "${{ github.event.ref }}" | sed 's/[^a-zA-Z0-9]/-/g')
          echo "sanitized_name=${sanitized_name}" >> $GITHUB_OUTPUT

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove preview directory
        run: |
          echo "Removing directory branches/${{ steps.sanitize.outputs.sanitized_name }}"
          rm -rf branches/${{ steps.sanitize.outputs.sanitized_name }}

      - name: Commit and push changes
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Cleaning up preview for branch ${{ github.event.ref }}"
          publish_branch: gh-pages
          force_orphan: false
          full_commit_message: "Clean up preview for branch ${{ github.event.ref }}"